CREATE USER hue WITH PASSWORD 'huepassword';
CREATE DATABASE hue WITH OWNER hue;
GRANT ALL PRIVILEGES ON DATABASE hue TO hue;

\c hue;
GRANT USAGE ON SCHEMA public TO hue;
GRANT CREATE ON SCHEMA public TO hue;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO hue;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO hue;