CREATE USER hive WITH PASSWORD 'hivepassword';
CREATE DATABASE metastore WITH OWNER hive;
GRANT ALL PRIVILEGES ON DATABASE metastore TO hive;

\c metastore;
GRANT USAGE ON SCHEMA public TO hive;
GRANT CREATE ON SCHEMA public TO hive;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO hive;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO hive;