-- CREATE DATABASE metastore;
-- CREATE USER hive WITH ENCRYPTED PASSWORD 'password';
-- GRANT ALL PRIVILEGES ON DATABASE metastore TO hive;
-- \c metastore postgres
-- GRANT ALL ON SCHEMA public TO hive;